### ISSUE TITLE
Difference in number of FIRE peaks in 'aligned data' vs 'align+phased data' from the same k-mer-variant-phasing run

### ISSUE THREAD

**Issue by RisaWatanabe** [fiberseq/FIRE#27]
Hi,

I ran FIRE_v0.06 on the pbmm2 output bam and the hiphase output bam from the same k-mervariant-phasing_v0.0.1-alpha run (https://github.com/mrvollger/k-mer-variant-phasing). To my surprise, number of rows for FIRE.bed.gz were slightly different (953,592 and 953,971 in pbmm2 and hiphase outputs, respectively). Pbmm2 output bam is used as an input for variantcalling/hiphasing in k-mer-variant-phasing, so I am wondering why there is an increase in number of FIRE elements for hiphase output bam. This sample had ~5.5 million reads.

I appreciate your help! Thank you!

**Comment by mrvollger** [comment]
The type of ML model used to call per read FIRE elements is usually deterministic but not guaranteed to be so. So that could be the case. 

Other ideas to check: 

1) Do the bam files truly contain the exact same number of reads and data? 

2) Are the files run with the same version of FIRE and ft. 

3) Are you checking the number of uncompressed lines? 

If that all ends up checking out I can take a look and see if there is a problem, but I'd need you to make a minimal test case from your data that I can run in ~5 minutes and reproduce the behavior.

**Comment by RisaWatanabe** [comment]
I was using 'cat | wc -l' instead of 'zcat | wc -l' on the FIRE.bed.gz. With zcat, I now see the same number of rows for the FIRE.bed.gz files. Thanks!
